name: Deploy to HuggingFace Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Deploy to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HG }}
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"

          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/amnabarzan/text_summarization || true

          git push hf main --force